### ISSUE TITLE
Supply Liquidity - Manual range option doesn't stay selected

### ISSUE THREAD

**Issue by Oli8** [QuickSwap/interface-v2#621]
**Bug Description**
When supplying liquidity we can't select the "manual" option anymore, it always get back to "automatic" after a few seconds

**Steps to Reproduce**

1. Go to any page to supply liquidity (e.g. https://quickswap.exchange/#/pools?currency0=0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270&currency1=0xa3fa99a148fa48d14ed51d610c367c61876997f1)
2. Click on "Manual" in "Select range" section and wait a few seconds
   
**Expected Behavior**
The manual option stays selected

**Additional Context**
Happens to me on desktop

**Comment by Aryan9592** [comment]
Works fine for me

**Comment by Oli8** [comment]
Yeah that was 8 months ago...
